In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import extinction

/home/jurados/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [4]:
sn_metadata = pd.read_csv('wiserep_spectra_metadata.csv', low_memory=False)
sn_metadata.head()

,Obj. ID,IAU name,Internal name/s,Obj. RA,Obj. DEC,Obj. Type,Redshift,Spec. ID,Obs-date,JD,...,Grating,Blaze,Lambda-min,Lambda-max,Del-Lambda,Contrib,Publish,Remarks,Created by,Creation date
0,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17656,1999-02-09 00:00:00.00,2451218.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
1,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17657,1999-02-10 00:00:00.00,2451219.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
2,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17658,1999-02-13 00:00:00.00,2451222.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
3,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17659,1999-02-23 00:00:00.00,2451232.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
4,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17660,1999-04-10 00:00:00.00,2451278.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53

In [5]:
sn_metadata.columns

Index(['Obj. ID', 'IAU name', 'Internal name/s', 'Obj. RA', 'Obj. DEC',
       'Obj. Type', 'Redshift', 'Spec. ID', 'Obs-date', 'JD', 'Phase (days)',
       'From', 'Telescope', 'Instrument', 'Observer/s', 'Reducer/s',
       'Source group', 'Public', 'Associated groups', 'End prop. period',
       'Ascii file', 'Fits file', 'Spec. type', 'Spec. quality',
       'Extinction-Corrected', 'WL Medium', 'WL Units',
       'Flux Unit Coefficient', 'Spec. units', 'Flux Calibrated By',
       'Exp-time', 'Aperture (slit)', 'HA', 'Airmass', 'Dichroic', 'Grism',
       'Grating', 'Blaze', 'Lambda-min', 'Lambda-max', 'Del-Lambda', 'Contrib',
       'Publish', 'Remarks', 'Created by', 'Creation date'],
      dtype='object')

In [30]:
sn_metadata['Spec. units']

0                             Other
1                             Other
2                             Other
3                             Other
4                             Other
                    ...
46446                         Other
46447    erg cm(-2) sec(-1) Ang(-1)
46448                         Other
46449    erg cm(-2) sec(-1) Ang(-1)
46450    erg cm(-2) sec(-1) Ang(-1)
Name: Spec. units, Length: 46451, dtype: object

In [16]:
wave = np.logspace(np.log10(910.), np.log10(30000.), 2000)

a_lambda = {'ccm89': extinction.ccm89(wave, 1.0, 3.1),
            'odonnell94': extinction.odonnell94(wave, 1.0, 3.1),
            'fitzpatrick99': extinction.fitzpatrick99(wave, 1.0),
            'fm07': extinction.fm07(wave, 1.0)}

a_lambda

{'ccm89': array([6.93015867, 6.88978376, 6.84981227, ..., 0.06928855, 0.06909376,
        0.06889951]),
 'odonnell94': array([6.93015867, 6.88978376, 6.84981227, ..., 0.06928855, 0.06909376,
        0.06889951]),
 'fitzpatrick99': array([6.29429344, 6.26503332, 6.23596073, ..., 0.07347002, 0.07331333,
        0.07315706]),
 'fm07': array([6.27850069, 6.25426847, 6.2301547 , ..., 0.04754595, 0.04739179,
        0.04723817])}

In [14]:
sn_metadata['Spec. units']

0                             Other
1                             Other
2                             Other
3                             Other
4                             Other
                    ...
46446                         Other
46447    erg cm(-2) sec(-1) Ang(-1)
46448                         Other
46449    erg cm(-2) sec(-1) Ang(-1)
46450    erg cm(-2) sec(-1) Ang(-1)
Name: Spec. units, Length: 46451, dtype: object

In [18]:
len(sn_metadata.Instrument.unique())

165

In [20]:
spectra_data = pd.read_pickle('spectra_ALeRCE20240630_x_wisrep_20240622.pkl')
len(spectra_data.snname.unique())

16281

In [27]:
previous_data = pd.read_csv('./data/master_lightcurves_ztfxtns.csv')
previous_data.columns

Index(['oid', 'fid', 'mjd', 'mag', 'e_mag', 'isdiffpos', 'rfid', 'candid',
       'pid', 'forced', 'source_id', 'type', 'redshift', 'filter'],
      dtype='object')

In [28]:
previous_data

,oid,fid,mjd,mag,e_mag,isdiffpos,rfid,candid,pid,forced,source_id,type,redshift,filter
0,ZTF17aaaipbw,2,58371.472130,19.820711,0.168984,-1.0,615120234.0,6.174721e+17,NaN,no,2017ixz,SNIIb,0.0240,orange
1,ZTF17aaaipbw,2,58374.515428,19.959324,0.179207,-1.0,615120234.0,6.205154e+17,NaN,no,2017ixz,SNIIb,0.0240,orange
2,ZTF17aaaipbw,2,58377.464780,19.914448,0.173840,-1.0,615120234.0,6.234648e+17,NaN,no,2017ixz,SNIIb,0.0240,orange
3,ZTF17aaaipbw,2,58380.473310,19.946108,0.188807,-1.0,615120234.0,6.264733e+17,NaN,no,2017ixz,SNIIb,0.0240,orange
4,ZTF17aaaipbw,2,58389.518542,19.876314,0.189524,-1.0,615120234.0,6.355185e+17,NaN,no,2017ixz,SNIIb,0.0240,orange
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215997,ZTF19abgbbzy,1,60437.283275,100.000000,100.000000,NaN,NaN,NaN,2.683283e+12,yes,2019lqo,SNII,0.0103,G
215998,ZTF19abgbbzy,3,60437.156065,17.361410,0.030229,NaN,NaN,NaN,2.683156e+12,yes,2024gzk,SNIIb,0.0103,NaN
215999,ZTF19abgbbzy,3,60437.156065,17.361410,0.030229,NaN,NaN,NaN,2.683156e+12,yes,2019lqo,SNII,0.0103,G
216000,ZTF19abgbbzy,2,60451.301435,18.351860,0.068626,NaN,NaN,NaN,2.697301e+12,yes,2024gzk,SNIIb,0.0103,NaN
216001,ZTF19abgbbzy,2,60451.301435,18.351860,0.068626,NaN,NaN,NaN,2.697301e+12,yes,2019lqo,SNII,0.0103,G

In [25]:
light_data = pd.read_pickle('df_lcs_ZTF-ALeRCE-lcclf20240517-transientsxTNS20240519_20240627.pkl')

In [26]:
light_data

,oid,candid,rfid,magpsf,sigmapsf,isdiffpos
0,ZTF17aaaadqv,624426581115015074,743120211.0,19.201122,0.123831,1
1,ZTF17aaaadqv,624463701115015007,743120111.0,19.533522,0.093020,1
2,ZTF17aaaadqv,625473001115015057,743120111.0,18.954454,0.080476,1
3,ZTF17aaaadqv,625513181115015031,743120211.0,18.518810,0.073205,1
4,ZTF17aaaadqv,626453721115015136,743120211.0,18.733690,0.073998,1
...,...,...,...,...,...,...
4610146,ZTF24aaoekwd,2713303613315015023,848120133.0,20.742992,0.145690,1
4610147,ZTF24aaoekwd,2713314783315015024,848120133.0,20.741930,0.110180,1
4610148,ZTF24aaoekwd,2713325943315015023,848120133.0,20.635244,0.123421,1
4610149,ZTF24aaoekwd,2713337103315015021,848120133.0,20.648048,0.101758,1
4610150,ZTF24aaoekwd,2713348273315015018,848120133.0,20.690287,0.127440,1

In [29]:
len(light_data.oid.unique())

69519