In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
spectra_metadata = pd.read_csv('wiserep_spectra_metadata.csv')
spectra_metadata.head()

/tmp/ipykernel_5492/350166623.py:1: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  spectra_metadata = pd.read_csv('wiserep_spectra_metadata.csv')

,Obj. ID,IAU name,Internal name/s,Obj. RA,Obj. DEC,Obj. Type,Redshift,Spec. ID,Obs-date,JD,...,Grating,Blaze,Lambda-min,Lambda-max,Del-Lambda,Contrib,Publish,Remarks,Created by,Creation date
0,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17656,1999-02-09 00:00:00.00,2451218.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
1,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17657,1999-02-10 00:00:00.00,2451219.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
2,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17658,1999-02-13 00:00:00.00,2451222.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
3,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17659,1999-02-23 00:00:00.00,2451232.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53
4,5875,SN 1999Z,NaN,155.65513,27.3555,SN IIn,0.051,17660,1999-04-10 00:00:00.00,2451278.5,...,NaN,NaN,3720.0,7540.5,1.499411,NaN,NaN,Data was ingested from the &lt;a href=&#039;ht...,Migration From WISeREP1.0,2013-07-08 09:12:53

In [5]:
spectra_data = pd.read_pickle('spectra_ALeRCE20240630_x_wisrep_20240622.pkl')
spectra_data.head()

,oid,snname,instrument,mjd,lambda_grid_min,lambda_grid_max,nlambda_grid,lambda_data_min,lambda_data_max,flux_lambda,e_flux_lambda
0,NaN,SN2021aefs,ESO-NTT,59560.313577,3206.34,10915.01,1838,3651.341553,9244.899935,"[1.91091e-16, 1.82705e-16, 1.97729e-16, 1.8812...","[7.185204317077444e-18, 1.5696079042524182e-17..."
1,NaN,SN2021aefs,P60,59559.436690,3206.34,10915.01,1838,3651.341553,9244.899935,"[1.91091e-16, 1.82705e-16, 1.97729e-16, 1.8812...","[7.185204317077444e-18, 1.5696079042524182e-17..."
2,ZTF20aburywx,SN2020rsc,Keck1,59226.000000,3206.34,10915.01,1838,3077.048800,10304.617000,"[2.03112e-16, 2.94057e-16, 2.56117e-16, 3.6180...","[5.4224405104354494e-17, 5.302190662866851e-17..."
3,NaN,SN2011kg,HST,55943.000000,3206.34,10915.01,1838,1903.618857,10615.877400,"[0.2298616, 0.1718295, 0.1137441, 0.0555966, -...","[0.0374385692592133, 0.03915660996486737, 0.04..."
4,NaN,SN2011kg,Keck1,55926.000000,3206.34,10915.01,1838,1903.618857,10615.877400,"[0.2298616, 0.1718295, 0.1137441, 0.0555966, -...","[0.0374385692592133, 0.03915660996486737, 0.04..."